AWSTemplateFormatVersion: "2010-09-09"
Description: "ScamReport Frontend - S3 Static Website (HTTP)"

Resources:
  ScamerBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "scamerreport-frontend-${AWS::AccountId}-${AWS::Region}"
      
      # ⭐ เปิด Static Website Hosting
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      
      # ⭐ ปิด Block Public Access
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      
      Tags:
        - Key: Project
          Value: ScamReport

  # Bucket Policy - Public Read
  ScamerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ScamerBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${ScamerBucket.Arn}/*"

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: scamerreport-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: scamerreport-web-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  WebsiteURL:
    Description: "Static website URL (HTTP)"
    Value: !GetAtt ScamerBucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"

  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref ScamerBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"